### ISSUE TITLE
how to set it up - question

### ISSUE THREAD

**Issue by OrionRandD** [ag91/writer-word-goals#1]
I have this in my init.el

;; writer-word-goals
(add-to-list 'load-path "~/_emacs.d_Orig/local-repo/writer-word-goals")
(require 'writer-word-goals)

But Emacs complains with this message

Warning (initialization): An error occurred while loading ‘/home/vagner/.emacs’:

error: Loading file /home/vagner/_emacs.d_Orig/local-repo/writer-word-goals/writer-word-goals.el failed to provide feature ‘writer-word-goals’

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by ag91** [comment]
I am going to look into this asap, but on top of my mind: any chance that `(require 'wwg)` works instead? I used an acronym for the feature name :P

**Comment by OrionRandD** [comment]
Nope. I have tried (require 'wwg) before  :(

**Comment by ag91** [comment]
I learned something new: it seems that the file needs to have the same name as the group to load via `load-path` :)
I tried on a clean Emacs installation and it works now.
@OrionRandD could you test that this works fine on your machine?

**Comment by OrionRandD** [comment]
So, how would you configure the whole thing?
Could you show here?

**Comment by ag91** [comment]
First update to the latest version of this package.
Following what you wrote above, you should need just this:
```
(add-to-list 'load-path "~/_emacs.d_Orig/local-repo/writer-word-goals")
(require 'wwg)
```

**Comment by OrionRandD** [comment]
thx a lot. I could set it up in my emacspers-gui and in my doom-emacs
:)

**Comment by OrionRandD** [comment]
As a suggestion, make a request for your package be part of the official
MELPA repository...

**Comment by ag91** [comment]
Amazing! Thanks for the suggestion: it is encouraging. I will look into it.

**Comment by OrionRandD** [comment]
Glad you liked it!
Thx for the package.
You can get help on this task in
IRC Freenode -> official channel is  #emacs
You can install Hexchat and reach Freenode from this app
apt install hexchat
https://freenode.net/

And for Doom Emacs, the official channel is in Discord - you need to
install Discord app in your Linux
https://discord.com/download
https://github.com/hlissner/doom-emacs
https://discord.com/invite/qvGgnVx

and add Doom Emacs channel to it
Now I will be a real Writer :)

**Comment by OrionRandD** [comment]
See also this video - this is a classical one
https://invidious.tube/watch?v=FtieBc3KptU&ckattempt=1

**Comment by ag91** [comment]
cool thanks @OrionRandD ! I will close the issue and looking into Melpa ;)
