### ISSUE TITLE
Missing Writegood-mode Functions

### ISSUE THREAD

**Issue by tpeacock19** [ag91/writer-word-goals#2]
It seems like you built this using your PR https://github.com/bnbeckwith/writegood-mode/pull/27 for writegood-mode. A number of those functions are used, but not present in the melpa/git version writegood.  I would suggest moving those functions to wwg since writegood does not seem too active.

looking forward to giving this a try!

**Comment by ag91** [comment]
Sorry! I got too excited and forgot to test in a clean installation XD

**Comment by ag91** [comment]
@tpeacock19 please reopen if it is still giving trouble
