### ISSUE TITLE
Function `wwg/set-goal-current-buffer` doesn't exist

### ISSUE THREAD

**Issue by erik-iwx** [ag91/writer-word-goals#5]
Following the README directions for setting stuff up, the function `wwg/set-goal-current-buffer` doesn't exist. Is there a new process for setup?

**Comment by ag91** [comment]
oops, sorry, you can use `wwg-mode` to set a word goal or
`wwg-editing-mode` for an editing goal.

When I submitted the package to Melpa they asked me to use minor modes
and we all forgot to review my README. I will fix that shortly.

Thanks for reporting!
